set (CMAKE_SYSTEM_NAME Windows)
set (MINGW TRUE)
set (CMAKE_ASM_COMPILER "C:\\ProgramData\\mingw64\\mingw64\\bin\\gcc.exe")
set (CMAKE_C_COMPILER "C:\\ProgramData\\mingw64\\mingw64\\bin\\gcc.exe")
set (CMAKE_CXX_COMPILER "C:\\ProgramData\\mingw64\\mingw64\\bin\\g++.exe")
set (OPENSSL_NO_ASM TRUE)
set (FIPS FALSE)
