set (CMAKE_SYSTEM_NAME Windows)
set (CMAKE_SYSTEM_PROCESSOR aarch64)
set (CMAKE_C_COMPILER "C:\\llvm-mingw\\bin\\clang.exe")
set (CMAKE_C_FLAGS "-ffunction-sections -fdata-sections -fuse-ld=lld --rtlib=compiler-rt")
set (CMAKE_C_COMPILER_TARGET aarch64-w64-windows-gnu)
set (CMAKE_CXX_COMPILER "C:\\llvm-mingw\\bin\\clang++.exe")
set (CMAKE_CXX_FLAGS "-ffunction-sections -fdata-sections -fuse-ld=lld --rtlib=compiler-rt --stdlib=libc++")
set (CMAKE_CXX_COMPILER_TARGET aarch64-w64-windows-gnu)
set (CMAKE_ASM_FLAGS "-ffunction-sections -fdata-sections -fuse-ld=lld --rtlib=compiler-rt")
